#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Przedmiot: Informatyka
# Kierunek studiów: Inżynieria transportu
# Semestr: zimowy
# Rok akademicki: 2020/2021
# Data (dzień.miesiąc.rok): 31.11.2020
# Imię: Piotr 
# Nazwisko: Nowicki
# Numer albumu ZUT: 

"""
W tym miejscu przepisać temat.
"""
